#:kivy 1.8.0
<HomeScreen>:
	Background:
		source: 'd7d7d7.png'
	BoxLayout:
		orientation: 'vertical'
		AnchorLayout:
			anchor_x:'center'
			anchor_y:'center'
			Button:
				id: 'HelpB'
				size_hint: None,None
				size:168,168
#				pos: root.width/2,root.heith/2
				background_normal: 'helpbutton.png'
				background_down: 'helpbutton.png'
				
		BoxLayout:
			orientation: 'horizontal'
			AnchorLayout:
				anchor_y:'bottom'
				anchor_x:'left'
				Button:
					id: 'ProfileB'
					size:80,60
					size_hint:0.999,None
					text:'Profile'
					background_normal: 'ff242f.png'
					background_down: 'ab1e25.png'
					border: (30,30,30,30)
			AnchorLayout:
				anchor_y:'bottom'
				anchor_x:'right'
				Button:
					id: 'MapB'
					size:80,60
					size_hint:0.999,None
					text:'Map'
					background_normal: 'ff242f.png'
					background_down: 'ab1e25.png'
<-Background>:
	canvas:
        Color:
            rgb: (1, 1, 1)
        Rectangle:
            texture: self.texture
            size: self.width + 20, self.height + 20
            pos: self.x + 0, self.y - 10
