#:kivy 1.8.0
<LogIn>:
	Backgruond:
		source: "ffcf6e.png"
	Label:
		id: Email
		text: "Email:"
		pos:-300,50
	SignUpB:
		source: "SignUpB.png"
	Logo:
		source: "Logo.png"


<-Backgruond>:
	canvas:
        Color:
            rgb: (1, 1, 1)
        Rectangle:
            texture: self.texture
            size: self.width + 20, self.height + 20
            pos: self.x - 10, self.y - 10
<-SignUpB>:
	canvas:
        Color:
            rgb: (1, 1, 1)
        Rectangle:
            texture: self.texture
            size: self.width + 500, self.height + 100
            pos: self.x - 320, self.y - 310

<-Logo>:
	canvas:
        Color:
            rgb: (1, 1, 1)
        Rectangle:
            texture: self.texture
            size: self.width + 20, self.height + 20
            pos: self.x + 50, self.y - 10
